### ISSUE TITLE
Feature request: Add a way to handle errors

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb-js#180]
Currently, when I do a `querySingle` query, I need to catch an error and check its message to know if the query returned no data or it's something else

```
if (error.message.includes("no data")) {
// handle error
}
```

I find it a bit confusing, since the error message is different from https://www.edgedb.com/docs/internals/protocol/errors#error-codes 

Maybe adding a `EdgedbErrorType` to the library will help?

**Comment by jaclarke** [comment]
Fixed in https://github.com/edgedb/edgedb-js/commit/636697e67bf5c82a2ead800daa02392697e3d88f.

`querySingle` will now return `null` if the result is an empty set. If you want to assert that there is *exactly* one result, use the new `queryRequiredSingle` method, which will throw `NoDataError` if the result is an empty set.
