### ISSUE TITLE
docs: note in literals section has odd styling

### ISSUE THREAD

**Issue by sbdchd** [edgedb/edgedb-js#240]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/7340772/153696741-6a885bb4-560a-4332-9c1f-5d3ab03e3ed3.png">

I'm not familiar with rst, but nothing sticks out to me:

https://github.com/edgedb/edgedb-js/blame/835050d398677e220a25fceee0ada2fb64a44a10/docs/literals.rst#L153-L156

**Comment by jaclarke** [comment]
Good catch. The issue is ReStructuredText has a quirk that double backticks don't get interpreted correctly if they're immediately surrounded by text on both sides, so unintuitively you need to add an escaped space after them that will get ignored, like so: ` ``bigint``\ s `.

(https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup)
