### ISSUE TITLE
`createClient` fails to find edgedb.toml or environment variable

### ISSUE THREAD

**Issue by mwarger** [edgedb/edgedb-js#378]
## Reproduction

I'm including an example repo here: https://github.com/mwarger/conference-demos

This work-in-progress demo repo has a bunch of stuff in it, so please disregard non-relevant code - the relevant file path is `libs/edgedb/src/lib/index.ts` - this has comments that also explain the basics of the issue.

## The issue

I have attempted to run a local edgedb project in multiple ways.  To start, letting the `createClient` call detect the edgedb.toml doesn't appear to work.  Failing that, I tried setting the EDGEDB_DSN to the instance name within an environment variable, both at the library level as well as at the root of the project.  This seems to be found, but it then tells me that the instance name is not valid, when it is (as proven below by manually entering the name).

I then tried manually setting the `dsn` within the config object, and this works.  

I also tried manually setting the `dsn`, but by using the actually EDGEDB_DSN environment variable, and this also worked (while also proving that the environment variable does indeed exist and is correct?).

Is there an issue here or am I expecting this to work in an incorrect way?  

As I noted above, there are ways to go about this so this isn't an urgent issue.  Thank you!

**Comment by jaclarke** [comment]
> letting the createClient call detect the edgedb.toml doesn't appear to work

The way edgedb-js looks for the `edgedb.toml` file is that starts in the current working directory (`process.cwd()`) and checks if the `edgedb.toml` file exists there, before walking up the file tree checking each parent directory until it finds `edgedb.toml` or fails. Since directly providing the instance name worked and the `edgedb.toml` file is in a nested directory in your repo, I think it may be that the cwd when you run your app is above the directory where `edgedb.toml` is.

> setting the EDGEDB_DSN to the instance name within an environment variable, both at the library level as well as at the root of the project. This seems to be found, but it then tells me that the instance name is not valid

There is actually an `EDGEDB_INSTANCE` env var (https://www.edgedb.com/docs/reference/connection#specifying-an-instance) which is the correct one to use here, `EDGEDB_DSN` expects a DSN in the form of `edgedb://USERNAME:PASSWORD@HOSTNAME:PORT/DATABASE`. Confusingly there's currently no corresponding `instance` option in the config object API. The `dsn` option does accept either a DSN or an instance name for backwards compatibility reasons, though really we should have an `instance` option as well to match the env vars. I think we just overlooked this (and we wouldn't recommend to use it anyway, since we don't recommend hardcoding instance connection details).

**Comment by mwarger** [comment]
It appears it is the `cwd` that's the issue in this case.  I ended up moving things to allow the automatic toml lookup.  I appreciate the explanation!
