### ISSUE TITLE
No Typescript errors when selecting a property that doesn't exist

### ISSUE THREAD

**Issue by papaspiridis** [edgedb/edgedb-js#405]
**Code**
The code causing the error.

```typescript
 const myQuery = e.select(e.Game, (game) => ({
    name: true,
    genre2: true, //typo is ignored in the editor
    filter: e.op(game.genre2, "=", "Sports"), //typo is underlined in the editor
  }));
```

**Schema**

Your application schema. 

```
module default {
  type Game {
    property name -> str;
    property genre -> str;
  }
}
```

**Error or desired behavior**
The above code results in the following error:
`UnhandledPromiseRejectionWarning: InvalidReferenceError: object type 'default::Game' has no link or property 'genre2'`
However, there are no errors in VS Code regarding the select, only in the filter.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/125977/182468952-6bbaebf6-6d31-4973-9a7b-a2d5181050af.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/125977/182469368-a2b881c0-70cf-45c1-ad2a-5087057dacbc.png">

**Versions (please complete the following information):**
 - OS: macOS
 - `EdgeDB version 2.0+88c1706`
 - `edgedb-js` version `0.21.1`

**Comment by Sikarii** [comment]
I believe this is intended to support computed fields: https://www.edgedb.com/docs/clients/js/select#computeds

**Comment by elprans** [comment]
> I believe this is intended to support computed fields: https://www.edgedb.com/docs/clients/js/select#computeds

Yeah, but here it isn't a computed, so ideally should still be a type error if possible.

**Comment by jaclarke** [comment]
If I remember right, there's no way to typecheck this correctly. Ideally we want to have the defined properties that we typecheck as `boolean`, and then a catchall for everything else that we want to typecheck as a qb expr:
```ts
type shape = {
  prop1: boolean;
  prop2: boolean;
} & {[computedKey: string]: Expr}
```
However since there's no overlap between `boolean` and `Expr`, that isn't valid, so we had to use a looser typecheck for computeds. To make it work correctly I think typescript would need some sort of negated type operator like `{[computedKey not in knownProps]: Expr}`.
