### ISSUE TITLE
Get line number causing an error in edgeql 

### ISSUE THREAD

**Issue by gsouf** [edgedb/edgedb-js#42]
Hi,

I see that the command line for edgeql supports line/col causing an error;

![image](https://user-images.githubusercontent.com/3215399/78531517-db60ed00-77e5-11ea-8c2e-f9bf58890f70.png)

Any ways we can get this feedback from the js client?

**Comment by jaclarke** [comment]
It looks like that information is encoded in the `attributes` field in the `ErrorResponse` message [documented here](https://edgedb.com/docs/internals/protocol/messages#ref-protocol-msg-error), and decoded in the [JS client here](https://github.com/edgedb/edgedb-js/blob/master/src/client.ts#L283), as a `Map<number, Buffer>`, but not exposed in the error.
I've found the keys for the `attrs` map [here](https://github.com/edgedb/edgedb/blob/master/edb/errors/base.py#L144), however the comment says they're subject to change/depreciation, so maybe that's why the attrs are not officially exposed, but it seems easy enough to modify the client if you need that information.

![image](https://user-images.githubusercontent.com/2085287/78667551-12f89380-78d1-11ea-89b5-baf1df616349.png)

**Comment by gsouf** [comment]
If it's not flagged as stable yet then I'll prefer to wait. Can we keep this issue opened until it's officially available?

**Comment by 1st1** [comment]
Yeah, we plan to implement Language Server Protocol for EdgeDB, so the current attributes are indeed unstable (and undocumented IIRC). If I may ask, what's your intended use case?

**Comment by gsouf** [comment]
@1st1 Thanks for the info.
I'm doing an ui to interact with edgedb, I want to be able to provide a visual feedback when an error occurs
