### ISSUE TITLE
Make it possible to get the generated query args types of outputted query files

### ISSUE THREAD

**Issue by tdolsen** [edgedb/edgedb-js#470]
Somewhat in relation to #469, would it be an idea to export the generated query args (and for that matter the result) beside the function declaration? Maybe making it generic as well?

I could see scenarios where I might want to use this, for consistency with input/output in mapping to DTOs and similar.

```ts
export interface SubmitAddressArgs extends QueryArgs {
  address: any;
}

export interface SubmitAddressResult extends QueryResult {
  id: string;
}

export async function submitAddress<A extends SubmitAddressArgs>(
  client: Client,
  args: A
): Promise<SubmitAddressResult> { ... }
```

Alternatively, to avoid polluting the export namespace, some utility types to help with inferring those types would help a lot on its own.

```ts
import { $inferArgs, $inferReturn, submitAddress } from "queries";

type SubmitAddressArgs = $inferArgs<typeof submitAddress>;
type SubmitAddressResult = $inferReturn<typeof submitAddress>;
```

I suppose the helper types could be as simple as:

```ts
type QueryFunc = (client: Client, args: QueryArgs) => Promise<QueryReturn>;
export type $inferArgs<T extends QueryFunc> = Parameters<T>[1];
export type $inferReturn<T extends QueryFunc> = ReturnType<T> extends Promise<infer R> ? R : never;
```

**Comment by scotttrinh** [comment]
@tdolsen 

Since this is pretty trivial, as you've pointed out, I'm going to close this as a bit out of scope. Our type helpers are generally targeted at the fact that a lot of our types are pretty opaque, or at least not really public, so we provide helpers to help you get to your more vanilla flavored types.

Let me know if you strongly disagree here and we can reconsider.
