### ISSUE TITLE
Feature request: Changelogs / GitHub releases

### ISSUE THREAD

**Issue by tdolsen** [edgedb/edgedb-js#565]
I currently find it hard to figure out what has changed when new versions are published to NPM, creating uncertainty to whether it's desired/safe to update at any given time.

It would be very helpful if there was an easy consumable changelog available for the different packages.

Even better if GitHub releases was published together with NPM release.

**Comment by BD103** [comment]
This is specifically applicable for the 1.1.0 release of the edgedb client, which has neither a Github release, Git tag, or changelog file. I had to manually `diff` the two versions, but that was uninformative due to the [amount of changes](https://github.com/edgedb/edgedb-js/files/11266926/edgedb.patch).

A [blog post](https://www.edgedb.com/blog) or update to the [changelog in the docs](https://www.edgedb.com/docs/changelog/index) would be helpful, but more of a hassle than just including notes in the repository.

**Comment by raddevon** [comment]
We have GitHub Actions that build changelogs, but there's currently a problem with them. This will be fixed once https://github.com/edgedb/edgedb-js/pull/572 is merged.

**Comment by scotttrinh** [comment]
Thanks for bringing this to our attention! I'll get the changes together for the last few releases and update this issue when it's ready.

**Comment by scotttrinh** [comment]
https://github.com/edgedb/edgedb-js/releases is up-to-date with the current releases! I'll keep a close eye on the release infrastructure to make sure our next release has a proper release.
