### ISSUE TITLE
auth-nextjs is not usable in the middleware

### ISSUE THREAD

**Issue by MiroslavPetrik** [edgedb/edgedb-js#779]
**Describe the bug**
The auth client cannot be used in the Next.js middleware. (and possibly edge runtimes)

<img width="820" alt="edgedb-middleware" src="https://github.com/edgedb/edgedb-js/assets/38855190/040b720b-f677-48ae-99c6-aea6b84358fc">

I got it running eventually, by extracting the `NextAuthSession` class into separate file, so it does not import the `node:crypto` transitively. Next, I needed to use the `createHttpClient` as the next.js middleware is like edge runtime, so the `createClient` does not work.
My code
```ts
import { cookies } from "next/headers";
import { NextAuthSession } from "@/auth/next/NextAuthSession";
import { env } from "@/env.mjs";
import { createHttpClient } from "edgedb";

export const client = createHttpClient({
  dsn: env.EDGEDB_DSN,
  // Note: when developing locally you will need to set tls  security to insecure,
  // because the development server uses  self-signed certificates which will cause api calls with  the fetch api to fail.
  tlsSecurity: "insecure",
});

export function getEdgeSession() {
  return new NextAuthSession(
    client,
// note hardcoded value, which is configurable via the NextAuth class from which the getSession method is extracted.
// just food for thoughts on how to refactor the package
    cookies().get("edgedb-session")?.value.split(";")[0],
  );
}

```

**Reproduction**
Include the code that is causing the error:

simple middleware usage:
```ts
// src/middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { auth } from "@/edgedb";

export async function middleware(request: NextRequest) {
  const session = auth.getSession();
  const loggedIn = await session.isLoggedIn();

  if (!loggedIn) {
    return NextResponse.redirect(new URL("/home", request.url));
  } else {
    return NextResponse.next();
  }
}

export const config = {
  matcher: ["/dashboard/:path*"],
};
```

**Expected behavior**
It should be possible to check the login query in the middleware.

**Versions (please complete the following information):**

- OS: win11
- EdgeDB version (e.g. `2.0`): 4
- EdgeDB CLI version (e.g. `2.0`):  EdgeDB CLI 4.0.2+b26c502
    "@edgedb/auth-nextjs": "^0.1.0-alpha.1",

**Comment by scotttrinh** [comment]
Ahh, the Edge runtime strikes again. I think we can probably get away with `WebCrypto` for this since all we need are: random values, SHA256 hashing, and a bytes <> base64url codec. I'll look into that.

**Comment by MiroslavPetrik** [comment]
The global `crypto` works.

Source: [Next.js edge api reference)(https://nextjs.org/docs/app/api-reference/edge)

**Comment by MiroslavPetrik** [comment]
There is another issue related to this and that is client components. The static methods from the `NextAuth` class from `shared.ts` very likely will be used in clients components, e.g. navigation links. I just ran in the same error, as I need check whether my navigation has some link active.

So as I see it, all the `shared.ts` could be package exports e.g. `@edgedb/auth-nextjs/shared`
then the method should be part of the shared or standalone, as it is static & that way we can drop the `Auth` import which makes the trouble
```
  isPasswordResetTokenValid(resetToken: string) {
    return Auth.checkPasswordResetTokenValid(resetToken);
  }
```
Also the static `getSession` method mentioned above can be in this shared/edge class.

**Comment by scotttrinh** [comment]
> The global crypto works.

Yep! The only thing we're missing is a native `base64url` encoder for the TypedArray that comes out of that. In Node.js, `Buffer` has a native way to decode a buffer directly to `base64url`. It's easy enough, we'll just implement it ourselves.

> Not sure if the support for the links in client components is one of your design goals here. But I can imagine multiple users could run into this, as navigation is often client component, and contains sign in/up/out urls/links.

Yeah, specifically, we cannot support querying from the client due to lack of RBAC on the client connection itself, so everything related to the database must happen on the server. In the future, as we evolve the `role` functionality in EdgeDB itself, we'll likely support querying from client components.

In the meantime, it definitely makes sense to have the server expose important URLs for use in client components. We should come up with some guidance here and maybe even expose a hook that can request this data from a server action (heavily cached) perhaps? Open to ideas on what is most idiomatic and ergonomic.

---

Thanks for the exploration so far, this is extremely valuable! Working on getting a `beta` release out this week, so will endeavor to answer all of these questions and smooth all of these pain points.
